#!/bin/sh
set -e

# Activate
env|grep '^IN_THE_ROOMS_ROOT=' || . ./activate

# Go through search pages
./download_searches.py

# This doesn't really detect the database's current state, so delete it and
# rebuild if something goes wrong.

# Schema
test -e "$IN_THE_ROOMS_ROOT/intherooms.db" ||
    sqlite3 "$IN_THE_ROOMS_ROOT/intherooms.db" < schema.sql

# Parse those pages.
for coords in $(ls -d searches-usa/*|cut -d/ -f2); do
    done_parsing="$IN_THE_ROOMS_ROOT/searches-usa/$coords/done-parsing"
    if test -f "$done_parsing"; then
        continue
    fi
    for page in $(ls searches-usa/$coords|cut -d. -f1|cut -d\/ -f2|grep -v done); do
        ./parse_search.py $coords $page
    done
    touch "$done_parsing"
done

./download_all_meetings.sh "$IN_THE_ROOMS_ROOT/intherooms.db"
./download_all_locations.sh "$IN_THE_ROOMS_ROOT/intherooms.db"
./parse_all_meetings.sh "$IN_THE_ROOMS_ROOT/intherooms.db"
./parse_all_locations.sh "$IN_THE_ROOMS_ROOT/intherooms.db"
