#!/bin/sh
set -e

# Activate
env|grep '^IN_THE_ROOMS_ROOT=' || . ./activate

# Go through search pages
for page in $(seq 1 400); do
    # Skip things that have already been downloaded.
    [ -e "$IN_THE_ROOMS_ROOT/searches/$page.html" ] && continue

    # Download a webpage.
    ./download_search.py $page

    # Test that it worked.
    if ! grep '<span class="current">'$page'</span>' \
        "$IN_THE_ROOMS_ROOT/searches/$page.html" > /dev/null; then
        mv "$IN_THE_ROOMS_ROOT/searches/$page.html" .last.html
        echo I stopped at page $page. If the script worked properly, this is because
        echo page $(($page - 1)) was the last page. Check .last.html to make sure.
        break
    fi

    sleep 1s
done

# This doesn't really detect the database's current state, so delete it and
# rebuild if something goes wrong.

# Schema
test -e "$IN_THE_ROOMS_ROOT/intherooms.db" ||
    sqlite3 "$IN_THE_ROOMS_ROOT/intherooms.db" < schema.sql

# Parse those pages.
for page in $(ls searches/*|cut -d. -f1|cut -d\/ -f2); do
    if [ $(sqlite3 $IN_THE_ROOMS_ROOT/intherooms.db "SELECT count(*) FROM meeting_search WHERE page = $page") = '0' ]; then
        ./parse_search.py $page
    else
        echo Page $page has already been parsed.
    fi
done

# Manually fix some weird records.
# sqlite3 intherooms.db < manual_fixes-ny.sql

./download_all_meetings.sh "$IN_THE_ROOMS_ROOT/intherooms.db"
./download_all_locations.sh "$IN_THE_ROOMS_ROOT/intherooms.db"
./parse_all_meetings.sh "$IN_THE_ROOMS_ROOT/intherooms.db"
./parse_all_locations.sh "$IN_THE_ROOMS_ROOT/intherooms.db"
